INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('1', 'First Book', 'First Author', '1000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('2', 'Second Book', 'Second Author', '2000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('3', 'Third Book', 'Third Author', '3000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('4', 'Fourth Book', 'Fourth Author', '4000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('5', 'Fifth Book', 'Fifth Author', '5000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('7', 'Sixth Book', 'Sixth Author', '6000');
